@file:Suppress("SpellCheckingInspection")

package io.github.tharukack.countrycodekit.internal

import io.github.tharukack.countrycodekit.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource

internal fun flagResourceFor(isoCode: String): DrawableResource? = when (isoCode.uppercase()) {
    "AD" -> Res.drawable.flag_ad
    "AE" -> Res.drawable.flag_ae
    "AF" -> Res.drawable.flag_af
    "AG" -> Res.drawable.flag_ag
    "AI" -> Res.drawable.flag_ai
    "AL" -> Res.drawable.flag_al
    "AM" -> Res.drawable.flag_am
    "AO" -> Res.drawable.flag_ao
    "AQ" -> Res.drawable.flag_aq
    "AR" -> Res.drawable.flag_ar
    "AS" -> Res.drawable.flag_as
    "AT" -> Res.drawable.flag_at
    "AU" -> Res.drawable.flag_au
    "AW" -> Res.drawable.flag_aw
    "AX" -> Res.drawable.flag_ax
    "AZ" -> Res.drawable.flag_az
    "BA" -> Res.drawable.flag_ba
    "BB" -> Res.drawable.flag_bb
    "BD" -> Res.drawable.flag_bd
    "BE" -> Res.drawable.flag_be
    "BF" -> Res.drawable.flag_bf
    "BG" -> Res.drawable.flag_bg
    "BH" -> Res.drawable.flag_bh
    "BI" -> Res.drawable.flag_bi
    "BJ" -> Res.drawable.flag_bj
    "BL" -> Res.drawable.flag_bl
    "BM" -> Res.drawable.flag_bm
    "BN" -> Res.drawable.flag_bn
    "BO" -> Res.drawable.flag_bo
    "BQ" -> Res.drawable.flag_bq
    "BR" -> Res.drawable.flag_br
    "BS" -> Res.drawable.flag_bs
    "BT" -> Res.drawable.flag_bt
    "BV" -> Res.drawable.flag_bv
    "BW" -> Res.drawable.flag_bw
    "BY" -> Res.drawable.flag_by
    "BZ" -> Res.drawable.flag_bz
    "CA" -> Res.drawable.flag_ca
    "CC" -> Res.drawable.flag_cc
    "CD" -> Res.drawable.flag_cd
    "CF" -> Res.drawable.flag_cf
    "CG" -> Res.drawable.flag_cg
    "CH" -> Res.drawable.flag_ch
    "CI" -> Res.drawable.flag_ci
    "CK" -> Res.drawable.flag_ck
    "CL" -> Res.drawable.flag_cl
    "CM" -> Res.drawable.flag_cm
    "CN" -> Res.drawable.flag_cn
    "CO" -> Res.drawable.flag_co
    "CP" -> Res.drawable.flag_cp
    "CR" -> Res.drawable.flag_cr
    "CU" -> Res.drawable.flag_cu
    "CV" -> Res.drawable.flag_cv
    "CW" -> Res.drawable.flag_cw
    "CX" -> Res.drawable.flag_cx
    "CY" -> Res.drawable.flag_cy
    "CZ" -> Res.drawable.flag_cz
    "DE" -> Res.drawable.flag_de
    "DG" -> Res.drawable.flag_dg
    "DJ" -> Res.drawable.flag_dj
    "DK" -> Res.drawable.flag_dk
    "DM" -> Res.drawable.flag_dm
    "DO" -> Res.drawable.flag_do
    "DZ" -> Res.drawable.flag_dz
    "EC" -> Res.drawable.flag_ec
    "EE" -> Res.drawable.flag_ee
    "EG" -> Res.drawable.flag_eg
    "EH" -> Res.drawable.flag_eh
    "ER" -> Res.drawable.flag_er
    "ES" -> Res.drawable.flag_es
    "ET" -> Res.drawable.flag_et
    "EU" -> Res.drawable.flag_eu
    "FI" -> Res.drawable.flag_fi
    "FJ" -> Res.drawable.flag_fj
    "FK" -> Res.drawable.flag_fk
    "FM" -> Res.drawable.flag_fm
    "FO" -> Res.drawable.flag_fo
    "FR" -> Res.drawable.flag_fr
    "GA" -> Res.drawable.flag_ga
    "GB" -> Res.drawable.flag_gb
    "GD" -> Res.drawable.flag_gd
    "GE" -> Res.drawable.flag_ge
    "GF" -> Res.drawable.flag_gf
    "GG" -> Res.drawable.flag_gg
    "GH" -> Res.drawable.flag_gh
    "GI" -> Res.drawable.flag_gi
    "GL" -> Res.drawable.flag_gl
    "GM" -> Res.drawable.flag_gm
    "GN" -> Res.drawable.flag_gn
    "GP" -> Res.drawable.flag_gp
    "GQ" -> Res.drawable.flag_gq
    "GR" -> Res.drawable.flag_gr
    "GS" -> Res.drawable.flag_gs
    "GT" -> Res.drawable.flag_gt
    "GU" -> Res.drawable.flag_gu
    "GW" -> Res.drawable.flag_gw
    "GY" -> Res.drawable.flag_gy
    "HK" -> Res.drawable.flag_hk
    "HM" -> Res.drawable.flag_hm
    "HN" -> Res.drawable.flag_hn
    "HR" -> Res.drawable.flag_hr
    "HT" -> Res.drawable.flag_ht
    "HU" -> Res.drawable.flag_hu
    "IC" -> Res.drawable.flag_ic
    "ID" -> Res.drawable.flag_id
    "IE" -> Res.drawable.flag_ie
    "IL" -> Res.drawable.flag_il
    "IM" -> Res.drawable.flag_im
    "IN" -> Res.drawable.flag_in
    "IO" -> Res.drawable.flag_io
    "IQ" -> Res.drawable.flag_iq
    "IR" -> Res.drawable.flag_ir
    "IS" -> Res.drawable.flag_is
    "IT" -> Res.drawable.flag_it
    "JE" -> Res.drawable.flag_je
    "JM" -> Res.drawable.flag_jm
    "JO" -> Res.drawable.flag_jo
    "JP" -> Res.drawable.flag_jp
    "KE" -> Res.drawable.flag_ke
    "KG" -> Res.drawable.flag_kg
    "KH" -> Res.drawable.flag_kh
    "KI" -> Res.drawable.flag_ki
    "KM" -> Res.drawable.flag_km
    "KN" -> Res.drawable.flag_kn
    "KP" -> Res.drawable.flag_kp
    "KR" -> Res.drawable.flag_kr
    "KW" -> Res.drawable.flag_kw
    "KY" -> Res.drawable.flag_ky
    "KZ" -> Res.drawable.flag_kz
    "LA" -> Res.drawable.flag_la
    "LB" -> Res.drawable.flag_lb
    "LC" -> Res.drawable.flag_lc
    "LI" -> Res.drawable.flag_li
    "LK" -> Res.drawable.flag_lk
    "LR" -> Res.drawable.flag_lr
    "LS" -> Res.drawable.flag_ls
    "LT" -> Res.drawable.flag_lt
    "LU" -> Res.drawable.flag_lu
    "LV" -> Res.drawable.flag_lv
    "LY" -> Res.drawable.flag_ly
    "MA" -> Res.drawable.flag_ma
    "MC" -> Res.drawable.flag_mc
    "MD" -> Res.drawable.flag_md
    "ME" -> Res.drawable.flag_me
    "MF" -> Res.drawable.flag_mf
    "MG" -> Res.drawable.flag_mg
    "MH" -> Res.drawable.flag_mh
    "MK" -> Res.drawable.flag_mk
    "ML" -> Res.drawable.flag_ml
    "MM" -> Res.drawable.flag_mm
    "MN" -> Res.drawable.flag_mn
    "MO" -> Res.drawable.flag_mo
    "MP" -> Res.drawable.flag_mp
    "MQ" -> Res.drawable.flag_mq
    "MR" -> Res.drawable.flag_mr
    "MS" -> Res.drawable.flag_ms
    "MT" -> Res.drawable.flag_mt
    "MU" -> Res.drawable.flag_mu
    "MV" -> Res.drawable.flag_mv
    "MW" -> Res.drawable.flag_mw
    "MX" -> Res.drawable.flag_mx
    "MY" -> Res.drawable.flag_my
    "MZ" -> Res.drawable.flag_mz
    "NA" -> Res.drawable.flag_na
    "NC" -> Res.drawable.flag_nc
    "NE" -> Res.drawable.flag_ne
    "NF" -> Res.drawable.flag_nf
    "NG" -> Res.drawable.flag_ng
    "NI" -> Res.drawable.flag_ni
    "NL" -> Res.drawable.flag_nl
    "NO" -> Res.drawable.flag_no
    "NP" -> Res.drawable.flag_np
    "NR" -> Res.drawable.flag_nr
    "NU" -> Res.drawable.flag_nu
    "NZ" -> Res.drawable.flag_nz
    "OM" -> Res.drawable.flag_om
    "PA" -> Res.drawable.flag_pa
    "PC" -> Res.drawable.flag_pc
    "PE" -> Res.drawable.flag_pe
    "PF" -> Res.drawable.flag_pf
    "PG" -> Res.drawable.flag_pg
    "PH" -> Res.drawable.flag_ph
    "PK" -> Res.drawable.flag_pk
    "PL" -> Res.drawable.flag_pl
    "PM" -> Res.drawable.flag_pm
    "PN" -> Res.drawable.flag_pn
    "PR" -> Res.drawable.flag_pr
    "PS" -> Res.drawable.flag_ps
    "PT" -> Res.drawable.flag_pt
    "PW" -> Res.drawable.flag_pw
    "PY" -> Res.drawable.flag_py
    "QA" -> Res.drawable.flag_qa
    "RE" -> Res.drawable.flag_re
    "RO" -> Res.drawable.flag_ro
    "RS" -> Res.drawable.flag_rs
    "RU" -> Res.drawable.flag_ru
    "RW" -> Res.drawable.flag_rw
    "SA" -> Res.drawable.flag_sa
    "SB" -> Res.drawable.flag_sb
    "SC" -> Res.drawable.flag_sc
    "SD" -> Res.drawable.flag_sd
    "SE" -> Res.drawable.flag_se
    "SG" -> Res.drawable.flag_sg
    "SH" -> Res.drawable.flag_sh
    "SI" -> Res.drawable.flag_si
    "SJ" -> Res.drawable.flag_sj
    "SK" -> Res.drawable.flag_sk
    "SL" -> Res.drawable.flag_sl
    "SM" -> Res.drawable.flag_sm
    "SN" -> Res.drawable.flag_sn
    "SO" -> Res.drawable.flag_so
    "SR" -> Res.drawable.flag_sr
    "SS" -> Res.drawable.flag_ss
    "ST" -> Res.drawable.flag_st
    "SV" -> Res.drawable.flag_sv
    "SX" -> Res.drawable.flag_sx
    "SY" -> Res.drawable.flag_sy
    "SZ" -> Res.drawable.flag_sz
    "TC" -> Res.drawable.flag_tc
    "TD" -> Res.drawable.flag_td
    "TF" -> Res.drawable.flag_tf
    "TG" -> Res.drawable.flag_tg
    "TH" -> Res.drawable.flag_th
    "TJ" -> Res.drawable.flag_tj
    "TK" -> Res.drawable.flag_tk
    "TL" -> Res.drawable.flag_tl
    "TM" -> Res.drawable.flag_tm
    "TN" -> Res.drawable.flag_tn
    "TO" -> Res.drawable.flag_to
    "TR" -> Res.drawable.flag_tr
    "TT" -> Res.drawable.flag_tt
    "TV" -> Res.drawable.flag_tv
    "TW" -> Res.drawable.flag_tw
    "TZ" -> Res.drawable.flag_tz
    "UA" -> Res.drawable.flag_ua
    "UG" -> Res.drawable.flag_ug
    "UM" -> Res.drawable.flag_um
    "UN" -> Res.drawable.flag_un
    "US" -> Res.drawable.flag_us
    "UY" -> Res.drawable.flag_uy
    "UZ" -> Res.drawable.flag_uz
    "VA" -> Res.drawable.flag_va
    "VC" -> Res.drawable.flag_vc
    "VE" -> Res.drawable.flag_ve
    "VG" -> Res.drawable.flag_vg
    "VI" -> Res.drawable.flag_vi
    "VN" -> Res.drawable.flag_vn
    "VU" -> Res.drawable.flag_vu
    "WF" -> Res.drawable.flag_wf
    "WS" -> Res.drawable.flag_ws
    "XK" -> Res.drawable.flag_xk
    "XX" -> Res.drawable.flag_xx
    "YE" -> Res.drawable.flag_ye
    "YT" -> Res.drawable.flag_yt
    "ZA" -> Res.drawable.flag_za
    "ZM" -> Res.drawable.flag_zm
    "ZW" -> Res.drawable.flag_zw
    "AC" -> Res.drawable.flag_sh_ac
    "TA" -> Res.drawable.flag_sh_ta
    else -> null
}
